# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jonas Rudi
email: jonas.rudi@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello, I'm just testing some stuff here!
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://jrudi.de" # the base hostname & protocol for your site
twitter_username: derjonasrudi
github_username:  jrudi

# Build settings
markdown: kramdown
